[general]
import = [
	"~/.config/alacritty/themes/catppuccin-macchiato.toml"
]

[window]
decorations = "None"
opacity = 0.8

[font]
#normal = { family = "FiraCode Nerd Font Mono", style= "Regular" }
#normal = { family = "JetBrainsMono Nerd Font", style= "Regular" }
normal = { family = "MonaspiceRn NFM", style= "Regular" }
#size = 12.4
size = 11

[keyboard]
bindings = [
    { key = "F10", mods = "Control|Shift", action = "ToggleMaximized" },
    { key = "F11", mods = "Control|Shift", action = "ToggleFullscreen" },
    { key = "F12", mods = "Control|Shift", action = "Minimize" },
    { key = "q", mods = "Control|Shift", action = "Quit" }
]
